### ISSUE TITLE
D3pie can not be loaded in nodejs

### ISSUE THREAD

**Issue by ddeath** [benkeen/d3pie#74]
require('d3pie') will produce:
    
    assert.js:92
      throw new assert.AssertionError({
            ^
    AssertionError: path must be a string
        at Module.require (module.js:362:3)
        at require (module.js:380:17)
        at _scriptName (/var/www/planeat/node_modules/d3pie/d3pie/d3pie.js:17:30)
        at Object.<anonymous> (/var/www/planeat/node_modules/d3pie/d3pie/d3pie.js:22:2)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)

Solution is remove require() in factory call. Like it is there:
https://github.com/umdjs/umd/blob/master/returnExports.js

**Comment by gilbarbara** [comment]
It just need a version bump now!

**Comment by benkeen** [comment]
Yeah sorry about that! I'll try to get a new version out tonight - if not, tomorrow.
